language: generic
matrix:
  include:
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python --version
        - python -m pip install --upgrade pip wheel
    - os: windows
      language: sh
      python: "2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python --version
        - python -m pip install --upgrade pip wheel
install: 
    - pip install .
    - pip install pytest
env:
    PYTEST_SKIP_EXCEL=yes
script:
    - py.test
    - python excel2img/excel2img.py
